#config_version=5
##! mode: cavetrap

#FATHOM

mode:
  start_events: start_mode_cavetrap
  stop_events: stop_mode_cavetrap
  priority: 275

event_player:
  mode_cavetrap_started: initialize_cavetrap
  ball_starting{ball==1}: cave_trap_initialize
  multiball_lock_cave_trap_full: cave_trap_ready_to_be_set, cave_trap_stage_1_complete
  cave_trap_open_shot_on_complete: cave_trap_open
  logicblock_cave_drop_seq_3_complete: cave_trap_open
  timer_cave_trap_start_escape_timer_complete: green_multiball_release_ready
  timer_cave_trap_multiball_show_timer_complete: reset_cave_trap 
  
  


multiball_locks:
  cave_trap:
    balls_to_lock: 1
    lock_devices: bd_right_saucer
    enable_events: initialize_cavetrap, ball_starting
    disable_events: cave_trap_multiball_complete
    reset_all_counts_events: reset_cave_trap
    reset_count_for_current_player_events: timer_cave_trap_multiball_show_timer_complete
    #locked_ball_counting_strategy: physical_only
    
sequences:
  cave_drop_seq:
    restart_events: left_green_trap_release_set
    persist_state: true
    start_enabled: true
    events:
      - cave_trap_ready_to_be_set
      - drop_green_3x_shot_hit
      
  cave_drop_seq_2:
    persist_state: true
    start_enabled: true
    events:
      - logicblock_cave_drop_seq_complete
      - drop_green_plus1x_shot_hit
      
  cave_drop_seq_3:
    persist_state: true
    start_enabled: true
    events:
      - logicblock_cave_drop_seq_2_complete
      - drop_green_plus1x_shot_hit

timers:
  cave_trap_lower_drop_timer: # drop targets raise and lower is staggered
    start_value: 1
    end_value: 0
    direction: down
    tick_interval: 500ms
    control_events:
      - action: start
        event: cave_trap_initialize
      - action: reset
        event: timer_cave_trap_lower_drop_timer_complete
        
  cave_trap_lower_drop_timer4: # drop targets raise and lower is staggered
    start_value: 1
    end_value: 0
    direction: down
    tick_interval: 500ms
    control_events:
      - action: start
        event: timer_cave_trap_mltplr_trg_timer_complete
      - action: reset
        event: timer_cave_trap_lower_drop_timer4_complete

  cave_trap_raise_drop_timer:  # drop targets raise and lower is staggered
    start_value: 1
    end_value: 0
    direction: down
    tick_interval: 500ms
    control_events:
      - action: start
        event: cave_trap_ready_to_be_set
      - action: reset
        event: timer_cave_trap_rasie_drop_timer_complete
        
  cave_trap_video_timer:  # to stop video
    start_value: 5
    end_value: 0
    direction: down
    tick_interval: 1s
    control_events:
      - action: start
        event: cave_trap_ready_to_be_set
      - action: reset
        event: timer_cave_trap_video_timer_complete
        
  cave_trap_start_escape_timer:  # a short pause before releasing the locked ball
    start_value: 1
    end_value: 0
    direction: down
    tick_interval: 500ms
    control_events:
      - action: start
        event: cave_trap_multiball_complete  #green_plus1x_5x_mltpr
      - action: reset
        event: timer_cave_trap_start_escape_timer_complete

  cave_trap_multiball_show_timer:  # time that multiball will be active
    start_value: 1
    end_value: 20
    direction: up
    tick_interval: 1s
    control_events:
      - action: start
        event: timer_cave_trap_start_escape_timer_complete
      - action: reset
        event: timer_cave_trap_multiball_show_timer_complete
        
  cave_trap_mltplr_trg_timer:  # reset multiplier targets after ball escape
    start_value: 1
    end_value: 4
    direction: up
    tick_interval: 1s
    control_events:
      - action: start
        event: timer_cave_trap_start_escape_timer_complete
      - action: reset
        event: timer_cave_trap_mltplr_trg_timer_complete


coil_player:
  cave_trap_initialize: c_drop_target_grn_1X_drop
  timer_cave_trap_left_drop_timer_complete: c_drop_target_grn_3X_drop
  timer_cave_trap_left_drop_timer2_complete: c_drop_target_grn_1X_drop
  timer_cave_trap_left_drop_timer3_complete: c_drop_target_grn_1X_drop
  timer_cave_trap_lower_drop_timer_complete: c_drop_target_grn_3X_drop
  cave_trap_ready_to_be_set: c_drop_target_grn_1X
  timer_cave_trap_raise_drop_timer_complete: c_drop_target_grn_3X
  #timer_cave_trap_mltplr_trg_timer_complete: c_drop_target_grn_1X
  #timer_cave_trap_left_drop_timer4_complete: c_drop_target_grn_3X
  

shots:
  grn_drop_target_3x:
    switch: s_grn_drop_target_3x
    profile: flash_profile

  grn_drop_target_plus1x:
    switch: s_grn_drop_target_plus1x
    profile: flash_profile

shot_groups:
  cave_trap_open_shot:
    shots: grn_drop_target_3x, grn_drop_target_plus1x
    reset_events:
      cave_trap_open_shot_on_complete: 2s

light_player:
  cave_trap_ready_to_be_set:
    led_rt_grn_arrow:
      priority: 4
      color: green
      fade: 500ms
  ball_starting{current_player.ball>=2}:
    led_rt_grn_arrow:
      priority: 1
      color: green
      fade: 500ms
  timer_cave_trap_start_escape_timer_complete:
    led_rt_grn_arrow:
      priority: 4
      color: off
      fade: 500ms      
  cave_trap_multiball_complete:
    led_ctr_dbl_wlit:
      color: yellow
      fade: 500ms
      

  timer_cave_trap_multiball_show_timer_complete:
    led_rt_grn_arrow:
      color: off
      fade: 500ms
    #gi:
      #color: white
      #fade: 500ms
    #bb_gi:
      #color: white
      #fade: 500ms

show_player:

  cave_trap_ready_to_be_set: # gi light show when ball locked
    gi_backbox_flash_show:
      loops: 4
      speed: 12
      
  cave_trap_ready_to_be_set.1:
    cave_trap_segment_display:
      loops: 3
      speed: 1
      priority: 2
      
  cave_trap_ready_to_be_set.2: # flash arrow "to release ball"
    color_cycle_show:
      loops: 3
      speed: 10
      priority: 10
      show_tokens:
        led: led_rt_grn_arrow
        color1: red
        color2: green

  grn_drop_target_3x_hit:
    color_cycle_show:
      loops: 3
      speed: 10
      priority: 10
      show_tokens:
        led: led_rt_grn_arrow
        color1: red
        color2: green

  grn_drop_target_plus1x_hit:
    color_cycle_show:
      loops: 3
      speed: 10
      priority: 11
      show_tokens:
        led: led_rt_grn_arrow
        color1: red
        color2: green
  
  #sequence_cave_drop_seq_started:
    #color_cycle_show:
      #loops: -1
      #speed: 2
      #priority: 9
      #show_tokens:
        #led: led_rt_grn_arrow
        #color1: green
        #color2: off  
  
        
  timer_cave_trap_multiball_show_timer_started:
    color_cycle_show:
      loops: -1
      speed: 4
      priority: 12
      show_tokens:
        led: led_rt_grn_arrow
        color1: red
        color2: green
    gi_backbox_cycle_show_3:  # gi show during multiball
      loops: -1
      speed: 30
      
  timer_cave_trap_multiball_show_timer_complete:
    color_cycle_show:
      action: stop
    gi_backbox_cycle_show_3:
      action: stop

  timer_cave_trap_start_escape_timer_started: # gi light show to get ready for ball escape from cave
    gi_backbox_flash_show:
      loops: 20
      speed: 44
      
  timer_cave_trap_start_escape_timer_complete:
    color_cycle_show:
      action: stop
      
  
slide_player:
  cave_trap_ready_to_be_set:
    cave_trap_slide:
      expire: 7s  #ball captured
  timer_cave_trap_video_timer_complete:
    cave_trap_slide:
      action: remove
      transition:
        type: fade
        duration: 1s

  
        
slides:
  cave_trap_slide:
#    - type: text
 #     font_name: ancienttext
#      color: red
#      text: Energy Level!
#      font_size: 100
#      expire: 5s
#      y: 40
#      anchor_y: bottom
 #     z: 5
    - type: video
      video: cave_trap_video
      height: 720
      width: 1280
      z: 10
      expire: 5s
      



