#config_version=5
#### FATHOM ####
#CobraPin Example Config
hardware:
    platform: opp
    driverboards: gen2
    segment_displays: light_segment_displays
    

#### CobraPin Serial Segment Displays ####
#create light group for each NeoSeg display.  120 leds for 8 digit type and 30 for 2-digit type
neoseg_displays:
  neoSeg_0:
    start_channel: 3-0-0
    size: 8digit
    light_template:
      type: w
      subtype: led
      color_correction_profile: NeoSeg_white
  neoSeg_1:
    start_channel: 3-0-120
    size: 8digit
    light_template:
      type: w
      subtype: led
      color_correction_profile: NeoSeg_white
  neoSeg_2:
    start_channel: 3-0-240
    size: 8digit
    light_template:
      type: w
      subtype: led
      color_correction_profile: NeoSeg_white
  neoSeg_3:
    start_channel: 3-0-360
    size: 2digit
    light_template:
      type: w
      subtype: led
      color_correction_profile: NeoSeg_white
  neoSeg_4:
    start_channel: 3-0-390
    size: 2digit
    light_template:
      type: w
      subtype: led
      color_correction_profile: NeoSeg_white
  neoSeg_5:
    start_channel: 3-0-420
    size: 8digit
    light_template:
      type: w
      subtype: led
      color_correction_profile: NeoSeg_white
      
#use light groups to arrange into a segment display
segment_displays:
  neoSegTop:
    number: 1
    size: 16
    integrated_dots: true
    use_dots_for_commas: true
    default_transition_update_hz: 30
    platform_settings:
      light_groups:
         - neoSeg_1
         - neoSeg_2
      type: 14segment
  neoSegBot:
    number: 1
    size: 16
    integrated_dots: true
    use_dots_for_commas: true
    default_transition_update_hz: 30
    platform_settings:
      light_groups:
         - neoSeg_0
         - neoSeg_5
      type: 14segment
  neoSegP3:
    number: 1
    size: 16
    integrated_dots: true
    use_dots_for_commas: true
    default_transition_update_hz: 30
    platform_settings:
      light_groups:
        - neoSeg_0
        #- neoSeg_1    ### you can group displays together
      type: 14segment
  neoSegP1:
    number: 1
    size: 16
    integrated_dots: true
    use_dots_for_commas: true
    default_transition_update_hz: 30
    platform_settings:
      light_groups:
        - neoSeg_1
        #- neoSeg_1
      type: 14segment
  neoSegP2:
    number: 1
    size: 16
    integrated_dots: true
    use_dots_for_commas: true
    default_transition_update_hz: 30
    platform_settings:
      light_groups:
        - neoSeg_2
        #- neoSeg_1
      type: 14segment
  neoSegball:
    number: 1
    size: 4
    integrated_dots: true
    use_dots_for_commas: true
    default_transition_update_hz: 30
    platform_settings:
      light_groups:
        - neoSeg_3
        #- neoSeg_1
      type: 14segment
  neoSegcredit:
    number: 1
    size: 4
    integrated_dots: true
    use_dots_for_commas: true
    default_transition_update_hz: 30
    platform_settings:
      light_groups:
        - neoSeg_4
        #- neoSeg_1
      type: 14segment
  neoSegP4:
    number: 1
    size: 16
    integrated_dots: true
    use_dots_for_commas: true
    default_transition_update_hz: 30
    platform_settings:
      light_groups:
        - neoSeg_5
        #- neoSeg_1
      type: 14segment
      
#use color_correction_profile whitepoint to adjust the brightness of each
#NeoSeg display
light_settings:
  color_correction_profiles:
    NeoSeg_red:
      whitepoint: [.8, .8, .8]
    NeoSeg_white:
      whitepoint: [.55, .55, .55]
    NeoSeg_blue:
      whitepoint: [.5, .5, .5]
    NeoSeg_orange:
      whitepoint: [.9, .9, .9]
    NeoSeg_yellow:
      whitepoint: [1, 1, 1]
    NeoSeg_green:
      whitepoint: [.5, .5, .5]
#### CobraOin Serial Segment Displays ####
    
bcp:
  connections:
    local_display:
      port: 5050

mpf-mc:
  bcp_port: 5050
    
#FATHOM

opp:
  #Use the USB ports defined by your OS for the two STM32 boards
      ports: COM13, COM14 #, COM5
  #USING SERIAL NUMBERS INSTEAD OF CHAINS
  #  Board 0 has serial number 0, Board 1 has serial number 1.
  #  This is convenient if your OS tends to reassign the serial port.
  #  MPF will automatically address the correct board even if the ports
  #     are swapped.

  #For multiple CobraPin boards in a game, you will either have to give 
  #  the STM32 boards on the second CobraPin board new serial numbers 
  #  (10 and 11 are suggested for the 2nd board since 2 is used by the 
  #  CobraPin Xpansion Board) 
  #  <OR> Use the chains section to assign a port to a board number. 
  #  Mixing these up could cause blown FETs, coils, and fuses. Proceed 
  #  with caution. Test without coil power and use the yellow coil LEDs 
  #  for feedback.
  #chains:
     #0: /dev/ttyACM0
     #1: /dev/ttyACM1
     
mpf:
     default_light_hw_update_hz: 50  # defaults to 50


psus:
    default:
    #Gives the capacitors extra time to recharge after firing a coil
    #  and eases the load on the power supply. Doesn't affect autofire
    #  devices like flippers, pops, slings.
        release_wait_ms: 50
    
    #DIRECT SWITCHES
  #switch numbers are labelled in silkscreen on the board

config:
    - keyboard.yaml
    - coils_config.yaml
    - lights_config.yaml
    - switches_config.yaml
    #- slides_config.yaml #welcome slide
    #- mc.yaml

modes:
    - base
    - awards
    - lane_change
    #- skillshot
    - extra_ball
    - bonus_collect
    - popbmpr
    - sixdropbank
    - ctrdropbank
    - lagoontrap
    - cavetrap
    - bluebonus
    - greenbonus
    - spinner
    - star_lane
    - high_score
    - spec_lanes
    #- bonus


game:
    balls_per_game: 3
    max_players: 2
    add_player_switch_tag: add_player

displays:
    window:
        width: 1280
        height: 720
window:
  height: 720
  width: 1280
  title: Fathom  
  resizable: true
  fullscreen: false
  borderless: true
  exit_on_escape: true
  show_cursor: false
  source_display: window
        
widget_styles:
    text_default:
        font_name: ancienttext
        font_size: 50
        adjust_top: 2
        adjust_bottom: 3
    space_title_huge:
        font_name: ancienttext
        font_size: 70
        antialias: true
        adjust_top: 3
        adjust_bottom: 3
    space_title:
        font_name: ancienttext
        font_size: 50
        antialias: true
        adjust_top: 2
        adjust_bottom: 3
    medium:
        font_name: ancienttext
        font_size: 60
        adjust_top: 1
        adjust_bottom: 1
    small:
        font_name: ancienttext
        font_size: 30
        adjust_top: 2
        adjust_bottom: 3
    tall_title:
        font_name: big_noodle_titling
        font_size: 20
    attract_mode_high_score_display_label:
        font_name: bobbithehippie
        font_size: 60
        anchor_x: right
        anchor_y: top
        x: center-90
        #bold: true
    attract_mode_high_score_display_name:
        font_name: bobbithehippie
        font_size: 75
        anchor_x: right
        anchor_y: top
        x: center+110
    attract_mode_high_score_display_score:
        font_name: ancienttext
        font_size: 75
        anchor_x: left
        anchor_y: top
        x: center+170
        number_grouping: true
        min_digits: 1
        
#slide_player:
    #init_done: welcome_slide

info_lights:    
#    player_1:
 #       light: l_led49 #led_player1
#    player_2:
#        light: l_led48 #led_player2
 #   player_3:
 #       light: l_led47 #led_player3
#    player_4:
#        light: l_led46 #led_player4
    tilt:
        light: l_bb_gi_37 #led_tilt
    game_over:
        light: l_bb_gi_39 #led_game_over
    match_00:
        light: l_bb_gi_56 #bb_match
    match_10:
        light: l_bb_gi_56 #bb_match
    match_20:
        light: l_bb_gi_56 #bb_match
    match_30:
        light: l_bb_gi_56 #bb_match
    match_40:
        light: l_bb_gi_56 #bb_match
    match_50:
        light: l_bb_gi_56 #bb_match
    match_60:
        light: l_bb_gi_56 #bb_match
    match_70:
        light: l_bb_gi_56 #bb_match
    match_80:
        light: l_bb_gi_56 #bb_match
    match_90:
        light: l_bb_gi_56 #bb_match       


#shows:
#- attract_light_show.yaml

##! mode: test_mode
#config_version=5
#show_player:
    #mode_attract_started: attract_display_loop
    #mode_attract_started: attract_light_show
      
playfields:
    playfield:
        tags: default
        default_source_device: bd_plunger #bd_trough  # use None in steps before 8

#coil_player:
    #s_right_inlane:
        #bell: c_bell
        #activation_switch: s_right_inlane

machine:
    balls_installed: 4
    min_balls: 1
 
ball_devices:
    bd_trough:
        ball_switches: s_trough_1, s_trough_2, s_trough_3, s_trough_4, s_trough_jam
        eject_coil: c_trough_eject
        confirm_eject_type: target
        tags: trough, home, drain
        jam_switch: s_trough_jam
        eject_coil_jam_pulse: 15ms
        eject_targets: bd_plunger
    bd_plunger:
        ball_switches: s_shooter_lane_eject
        eject_coil: c_shooter_launch
        mechanical_eject: true
        eject_timeouts: 5s
    bd_top_saucer:
        ball_switches: s_top_saucer
        eject_coil: c_saucer_top
        eject_timeouts: 750ms
    bd_right_saucer:
        ball_switches: s_right_saucer
        eject_coil: c_saucer_right
        eject_timeouts: 750ms                
flippers:
    left_flipper:
        main_coil: c_flipper_left_main
        hold_coil: c_flipper_left_hold
        activation_switch: s_left_flipper
        label: left main flipper
        #enable_events: #machine_reset_phase_3 #temp, normally enabled when ball is in trough.
    right_flipper:
        main_coil: c_flipper_right_main
        hold_coil: c_flipper_right_hold
        activation_switch: s_right_flipper
        label: right main flipper
        #enable_events: #machine_reset_phase_3 #temp, normally enabled when ball is in trough.
    right_flipper_upper:
        main_coil: c_flipper_upper_right_main
        hold_coil: c_flipper_upper_right_hold
        activation_switch: s_right_flipper_upper
        label: right upper flipper
        #enable_events: #machine_reset_phase_3 #temp, normally enabled when ball is in trough.

autofire_coils:
    left_slingshot:
        coil: c_slingshot_left
        switch: s_left_sling_shot
        #enable_events: #machine_reset_phase_3 #temp, normally enabled when ball is in trough.
    right_slingshot:
        coil: c_slingshot_right
        switch: s_right_sling_shot
        #enable_events: #machine_reset_phase_3 #temp, normally enabled when ball is in trough.
    pop_bmp_left:
        coil: c_pop_bmp_left
        switch: s_left_pop_bumper
        #enable_events: #machine_reset_phase_3 #temp, normally enabled when ball is in trough.
    pop_bmp_right:
        coil: c_pop_bmp_right
        switch: s_right_pop_bumper
        #enable_events: #machine_reset_phase_3 #temp, normally enabled when ball is in trough.
    pop_bmp_bottom:
        coil: c_pop_bmp_bottom
        switch: s_lower_pop_bumper
        #enable_events: #machine_reset_phase_3 #temp, normally enabled when ball is in trough.
        
drop_targets:
    left1_1:
        switch: s_left_drop1_target_1
    left1_2:
        switch: s_left_drop1_target_2
    left1_3:
        switch: s_left_drop1_target_3
    left2_1:
        switch: s_left_drop2_target_1
    left2_2:
        switch: s_left_drop2_target_2
    left2_3:
        switch: s_left_drop2_target_3
    ctr_1:
        switch: s_ctr_drop_target_1
    ctr_2:
        switch: s_ctr_drop_target_2
    ctr_3:
        switch: s_ctr_drop_target_3
        
        
drop_target_banks:
    left_bank1:
        drop_targets: left1_1, left1_2, left1_3, left2_1, left2_2, left2_3
        reset_coils: c_drop1_target_left, c_drop2_target_left
        reset_on_complete: 1s
    #left_bank2:
        #drop_targets: left2_1, left2_2, left2_3
        #reset_coils: c_drop2_target_left
        #reset_on_complete: 1s
    ctr_bank:
        drop_targets: ctr_1, ctr_2, ctr_3
        reset_coils: c_drop_target_ctr
        reset_on_complete: 1s
spinners:
  fathom_spinner:
    switch: s_spinner
    active_ms: 200
    idle_ms: 2000    
#ball_holds:
    #kicker_mode:
        #balls_to_hold: 1
        #hold_devices: bd_left_saucer
        #release_one_events: medium_metal_complete
        
sound_system:
    tracks:
        voice:
            volume: 1
            priority: 2
            simultaneous_sounds: 1
            preload: true
        sfx:
            volume: 1
            priority: 1
            preload: true
            simultaneous_sounds: 8
        music:
            volume: 0.5
            simultaneous_sounds: 1
    buffer: 1024  # previous value was 512
    frequency: 44100
    channels: 2
    master_volume: 1
    enabled: true
    
assets:
    sounds:
        default:
            track: sfx
    music:
        track: music
        mode_end_action: stop
    sfx:
        track: sfx
        load: preload
    voice:
        e:
        track: voice
        load: preload
        ducking:
              target: sfx
              delay: 0
              attack: 0.1 sec
              attenuation: 0.5
              release_point: 0.5 sec
              release: 0.2 sec
        
#images:
#    bonus_image_1:
#        width: 1366
#        height: 768
#        file: bonus_image_1.jpg

        
videos:
    attract_loop_video:
        width: 1280
        height: 720
        file: attract_loop_video.mp4
    start_video:
        width: 1280
        height: 720
        file: start_video.mp4
    ball_saved_video:
        width: 1280
        height: 720
        file: ball_saved_video.mp4
    cave_trap_video:
        width: 1280
        height: 720
        file: cave_trap_video.mp4
    extra_ball_video:
        width: 1280
        height: 720
        file: extra_ball_video.mp4
    extra_ball_2_video:
        width: 1280
        height: 720
        file: extra_ball_2_video.mp4
    spinner_video:
        width: 1280
        height: 720
        file: spinner_video.mp4
    spinner_bonus_video:
        width: 1280
        height: 720
        file: spinner_bonus_video.mp4
    green_drop_video:
        width: 1280
        height: 720
        file: green_drop_video.mp4
    blue_drop_video:
        width: 1280
        height: 720
        file: blue_drop_video.mp4
    3X_mltplr_video:
        width: 1280
        height: 720
        file: 3X_blue_video.mp4
    4X_mltplr_video:
        width: 1280
        height: 720
        file: 4X_blue_video.mp4
    5X_mltplr_video:
        width: 1280
        height: 720
        file: 5X_blue_video.mp4
    lane_change_1_video:
        width: 1280
        height: 720
        file: lane_change_1_video.mp4
    lane_change_2_video:
        width: 1280
        height: 720
        file: lane_change_2_video.mp4
    lane_change_3_video:  # muliball starting video
        width: 1280
        height: 720
        file: lane_change_3_video.mp4
    lane_change_4_video:  # muliball loop video
        width: 1280
        height: 720
        file: lane_change_4_video.mp4
    ball_end_video:
        width: 1280
        height: 720
        file: ball_end_video.mp4
    pop_1_video:
        width: 1280
        height: 720
        file: pop_1_video.mp4
    pop_2_video:
        width: 1280
        height: 720
        file: pop_2_video.mp4
    pop_3_video:
        width: 1280
        height: 720
        file: pop_3_video.mp4
    spec_lanes_1_video:
        width: 1280
        height: 720
        file: spec_lanes_1_video.mp4
    spec_lanes_2_video:
        width: 1280
        height: 720
        file: spec_lanes_2_video.mp4
    spec_lanes_3_video:
        width: 1280
        height: 720
        file: spec_lanes_3_video.mp4
    spec_lanes_4_video:
        width: 1280
        height: 720
        file: spec_lanes_4_video.mp4
    sling_1_video:
        width: 1280
        height: 720
        file: sling_1_video.mp4
    sling_2_video:
        width: 1280
        height: 720
        file: sling_2_video.mp4
        
images:
    hi_score_image_1:
        width: 1280
        height: 720
        file: hi_score_image_1.jpg

player_vars:
  green_collect_hit_total:
    value_type: int
    initial_value: 1
  blue_collect_hit_total:
    value_type: int
    initial_value: 1
  blue_3x_bonus_pf_multiplier:
    value_type: int
    initial_value: 1  
  green_3x_bonus_pf_multiplier:
    value_type: int
    initial_value: 1
    
#machine_vars:
  #high_score:
    

