#config_version=5
##! mode: greenbonus

#FATHOM

mode:
  start_events: start_mode_greenbonus
  stop_events: stop_mode_greenbonus
  priority: 450
  
 
event_player:
  mode_greenbonus_started: initialize_greenbonus
  drop_green_3x_shot_hit: green_3x_bonus_active, cave_trap_stage_2_complete
  drop_green_plus1x_shot_hit: green_plus1x_count_up
  green_plus1x_count_done{count==2}: green_plus1x_raise_again, cave_trap_stage_3_complete
  green_plus1x_count_done{count==3}: green_plus1x_5x_mltpr, cave_trap_stage_3_achieved, cave_trap_level_1_complete
  
  
  
  
shots:
  drop_green_3x_shot:
    switch: s_grn_drop_target_3x
    enable_events:
      - mode_ball_starting_show_ended
      - timer_cave_trap_multiball_show_timer_complete
    disable_events:
      - start_ball_starting_show
      - timer_cave_trap_start_escape_timer_complete
    profile: flash_profile
    
  drop_green_plus1x_shot:
    switch: s_grn_drop_target_plus1x
    enable_events:
      - mode_ball_starting_show_ended
      - timer_cave_trap_multiball_show_timer_complete
    disable_events:
      - start_ball_starting_show 
      - timer_cave_trap_start_escape_timer_complete      
    profile: flash_profile


### Since Fathom typically has a 3 inline drop target assembly but this Fathom only
###  has 2 inline targets, the 2nd target (plus1x) needs to be hit twice to achieve
###  the 5x multiplier.


    
counters:
  green_plus1x_count:
    count_events: green_plus1x_count_up 
    events_when_hit: green_plus1x_count_done
    starting_count: 1
    direction: up
    count_complete_value: 4
    reset_on_complete: true
    persist_state: true
    start_enabled: true
    disable_on_complete: false
    enable_events:
      #- timer_green_mltplr_pause_timer_complete
      - cave_trap_ready_to_be_set
      - timer_cave_trap_mltplr_trg_timer_complete
    disable_events:
      #- ball_starting
      #- left_green_trap_release_set
      #- cave_trap_multiball_complete
    restart_events: green_plus1x_count_complete, reset_cave_trap #ball_starting  ###green_inline_bank_reset
    
timers:
  green_plus1x_raise_again_timer:
    start_value: 1
    end_value: 0
    direction: down
    tick_interval: 500ms
    control_events:
      - action: start
        event: green_plus1x_raise_again
      - action: reset
        event: timer_green_plus1x_raise_again_timer_complete
        
  green_mltplr_pause_timer:
    start_value: 5
    end_value: 0
    direction: down
    tick_interval: 1s
    control_events:
      - action: start
        event: ball_starting
      - action: reset
        event: timer_green_mltplr_pause_timer_complete
        
  timer_down_3X_mltplr_video:
        start_value: 5
        end_value: 0
        direction: down
        tick_interval: 1s
        start_running: no
        control_events:
            - action: start
              event: slide_3X_slide_active
            - action: reset
              event: timer_timer_down_3X_mltplr_video_complete
              
  timer_down_4X_mltplr_video:
        start_value: 5
        end_value: 0
        direction: down
        tick_interval: 1s
        start_running: no
        control_events:
            - action: start
              event: slide_4X_slide_active
            - action: reset
              event: timer_timer_down_4X_mltplr_video_complete
              
  timer_down_5X_mltplr_video:
        start_value: 5
        end_value: 0
        direction: down
        tick_interval: 1s
        start_running: no
        control_events:
            - action: start
              event: slide_5X_slide_active
            - action: reset
              event: timer_timer_down_5X_mltplr_video_complete
              
  
    
coil_player:
  timer_green_plus1x_raise_again_timer_complete: c_drop_target_grn_1X  
    
    
    
variable_player:

# initial bonus multiplier set in bonus_collect mode.

  green_3x_bonus_active:
    green_3x_bonus_pf_multiplier:
      int: 3
      action: set
  
  green_plus1x_raise_again:
    green_3x_bonus_pf_multiplier:
      int: 4
      action: set
      
  green_plus1x_5x_mltpr:
    green_3x_bonus_pf_multiplier:
      int: 5
      action: set
      
  drop_green_3x_shot_hit:
    score: 10000
  
  drop_green_plus1x_shot_hit:
    score: 30000
      
show_player:
  cave_trap_stage_2_achieved:
    3X_green_segment_display:
      loops: 3
      speed: 1
      priority: 2
  cave_trap_stage_3_achieved:
    4X_green_segment_display:
      loops: 3
      speed: 1
      priority: 2
  cave_trap_multiball_complete:
    5X_green_segment_display:
      loops: 3
      speed: 1
      priority: 2
      
light_player:   ### using achievements so the multiball tracking is not reset between balls.
  #green_3x_bonus_active:
  cave_trap_stage_2_achieved:
        led_grn_3X:
            color: green
            fade: 500ms
  #green_plus1x_raise_again:
  green_plus1x_count_done{count==2}:
        led_grn_4X:
            color: orange
            fade: 500ms
  #green_plus1x_5x_mltpr:
  green_plus1x_count_done{count==3}:
        led_grn_5X:
            color: white
            fade: 500ms
            
slide_player:
  cave_trap_stage_2_achieved:  3X_slide  #3X bonus
  timer_timer_down_3X_mltplr_video_complete:
    3X_slide:
      action: remove
      transition:
        type: fade
        duration: 1s
  green_plus1x_count_done{count==2}:  4X_slide  #4X bonus
  timer_timer_down_4X_mltplr_video_complete:
    4X_slide:
      action: remove
      transition:
        type: fade
        duration: 1s
  green_plus1x_count_done{count==3}:  5X_slide  #5X bonus
  timer_timer_down_5X_mltplr_video_complete:
    5X_slide:
      action: remove
      transition:
        type: fade
        duration: 1s
        
slides:
  3X_slide:
#    - type: text
 #     font_name: ancienttext
#      color: red
#      text: Energy Level!
#      font_size: 100
#      expire: 5s
#      y: 40
#      anchor_y: bottom
 #     z: 5
    - type: video
      video: 3X_mltplr_video
      height: 720
      width: 1280
      z: 10
      expire: 5s
  4X_slide:
    - type: video
      video: 4X_mltplr_video
      height: 720
      width: 1280
      z: 10
      expire: 5s
  5X_slide:
    - type: video
      video: 5X_mltplr_video
      height: 720
      width: 1280
      z: 10
      expire: 5s          